In [1]:
print("K-Means")

import gensim 
import gensim.models.keyedvectors as word2vec
w2v_model = word2vec.KeyedVectors.load('w2v.model')

vocabulary = []
for word in w2v_model.vocab.keys():
    vocabulary.append(word)
print(len(vocabulary))

K-Means


/Users/linhnvc/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


225822


In [2]:
content = """
Trump cáo buộc đảng Dân chủ đang theo đuổi "nỗ lực đảo chính bất hợp pháp, mang tính đảng phái" khi tìm cách luận tội ông.

"Chính các người mới là phe can thiệp vào bầu cử Mỹ, phá vỡ nền dân chủ của đất nước và cản trở công lý. Điều này không là gì khác ngoài một nỗ lực đảo chính bất hợp pháp, mang tính đảng phái và sẽ thất bại nặng nề tại hòm phiếu, dựa trên tình hình gần đây", Tổng thống Mỹ Donald Trump viết trong lá thư dài 6 trang gửi Chủ tịch Hạ viện Nancy Pelosi vào hôm qua để chỉ trích cuộc điều tra luận tội của phe Dân chủ. 

Ông chủ Nhà Trắng viết thêm rằng bà Pelosi "đang biến hạ viện từ cơ quan lập pháp được kính trọng thành một phòng xử án của cuộc đàn áp đảng phái", đồng thời "gần như không thèm che giấu sự thù ghét" đối với ông. 

"Bằng cách thúc đẩy cuộc luận tội trái phép đó, các người đang vi phạm lời thề nhậm chức, phá vỡ lòng trung thành với hiến pháp và tuyên chiến với nền dân chủ Mỹ. Các người coi dân chủ là kẻ thù của chính mình", Trump viết.
Bức thư của Trump được gửi đi trong bối cảnh hạ viện, nơi đảng Dân chủ chiếm đa số, dự kiến bỏ phiếu vào hôm nay về các điều khoản luận tội Tổng thống Mỹ và khả năng cao sẽ thông qua để đưa Trump ra xét xử tại thượng viện. Ông gần như chắc chắn sẽ trở thành tổng thống Mỹ thứ ba trong lịch sử bị luận tội. 

Trước đó, Ủy ban Tư pháp Hạ viện đã thông qua hai điều khoản luận tội Trump, bao gồm lạm dụng quyền lực và cản trở quốc hội. Phe Dân chủ cáo buộc Trump thúc ép Ukraine điều tra cha con cựu phó tổng thống Mỹ Joe Biden, đối thủ của Trump trong cuộc bầu cử năm 2020, gây nguy hiểm cho hiến pháp Mỹ, an ninh quốc gia và tính công bằng của bầu cử. 

Trong khi đó, đảng Cộng hòa vẫn cố gắng bảo vệ Trump, khi lãnh đạo phe đa số tại thượng viện Mitch McConnell bác bỏ yêu cầu của đảng Dân chủ nhằm đề nghị 4 quan chức cũ và đương nhiệm ra làm chứng tại phiên tòa luận tội dự kiến diễn ra ở thượng viện vào tháng tới. 

Hạ viện Mỹ mở cuộc điều tra luận tội Trump từ tháng 9, sau khi một người tố giác giấu tên đệ đơn cáo buộc Tổng thống Mỹ dùng gói viện trợ quân sự để gây áp lực lên người đồng cấp Ukraine Volodymyr Zelensky. Tuy nhiên, Trump phủ nhận các cáo buộc và gọi cuộc điều tra luận tội là trò lừa bịp.
"""

contents_parsed = content.lower() 
contents_parsed = contents_parsed.replace('\n', ' ')
contents_parsed = contents_parsed.strip() 

import nltk
sentences = nltk.sent_tokenize(contents_parsed)

i = 0
for sentence in sentences:
    print(i,"===", sentence)
    i += 1

0 === trump cáo buộc đảng dân chủ đang theo đuổi "nỗ lực đảo chính bất hợp pháp, mang tính đảng phái" khi tìm cách luận tội ông.
1 === "chính các người mới là phe can thiệp vào bầu cử mỹ, phá vỡ nền dân chủ của đất nước và cản trở công lý.
2 === điều này không là gì khác ngoài một nỗ lực đảo chính bất hợp pháp, mang tính đảng phái và sẽ thất bại nặng nề tại hòm phiếu, dựa trên tình hình gần đây", tổng thống mỹ donald trump viết trong lá thư dài 6 trang gửi chủ tịch hạ viện nancy pelosi vào hôm qua để chỉ trích cuộc điều tra luận tội của phe dân chủ.
3 === ông chủ nhà trắng viết thêm rằng bà pelosi "đang biến hạ viện từ cơ quan lập pháp được kính trọng thành một phòng xử án của cuộc đàn áp đảng phái", đồng thời "gần như không thèm che giấu sự thù ghét" đối với ông.
4 === "bằng cách thúc đẩy cuộc luận tội trái phép đó, các người đang vi phạm lời thề nhậm chức, phá vỡ lòng trung thành với hiến pháp và tuyên chiến với nền dân chủ mỹ.
5 === các người coi dân chủ là kẻ thù của chính mình", t

In [3]:
from pyvi import ViTokenizer
import numpy as np 

X = []
for sentence in sentences:
    
    # sentence = gensim.utils.simple_preprocess(sentence)
    # sentence = ' '.join(sentence)
    sentence_tokenized = ViTokenizer.tokenize(sentence)
    # print(sentence_tokenized)
    words = sentence_tokenized.split(" ")
    sentence_vec = np.zeros((128))
    for word in words:
        if word in vocabulary:
            sentence_vec+=w2v_model[word]
    X.append(sentence_vec)

print(len(X))

13


In [4]:
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin_min

n_clusters = 3
kmeans = KMeans(n_clusters=n_clusters)
kmeans = kmeans.fit(X)

print("K-Means Clustering\n")
avg = []
for j in range(n_clusters):
    print("Cụm", j+1)
    idx = np.where(kmeans.labels_ == j)[0]
    print(idx)
    avg.append(np.mean(idx))
    print("Thứ tự trung bình: ", round(np.mean(idx), 2))
    print("="*115)
closest, _ = pairwise_distances_argmin_min(kmeans.cluster_centers_, X)
print("Các câu gần", n_clusters, "tâm cụm nhất",closest)
ordering = sorted(range(n_clusters), key=lambda k: avg[k])
# print(ordering)
print("\nKết quả tóm tắt:\n")
summary = ' '.join(["(Câu " + str(closest[idx]) + ") " + sentences[closest[idx]] for idx in ordering])
print(summary)

K-Means Clustering

Cụm 1
[ 3  4  9 11]
Thứ tự trung bình:  6.75
Cụm 2
[ 2  6 10]
Thứ tự trung bình:  6.0
Cụm 3
[ 0  1  5  7  8 12]
Thứ tự trung bình:  5.5
Các câu gần 3 tâm cụm nhất [ 9 10  7]

Kết quả tóm tắt:

(Câu 7) ông gần như chắc chắn sẽ trở thành tổng thống mỹ thứ ba trong lịch sử bị luận tội. (Câu 10) trong khi đó, đảng cộng hòa vẫn cố gắng bảo vệ trump, khi lãnh đạo phe đa số tại thượng viện mitch mcconnell bác bỏ yêu cầu của đảng dân chủ nhằm đề nghị 4 quan chức cũ và đương nhiệm ra làm chứng tại phiên tòa luận tội dự kiến diễn ra ở thượng viện vào tháng tới. (Câu 9) phe dân chủ cáo buộc trump thúc ép ukraine điều tra cha con cựu phó tổng thống mỹ joe biden, đối thủ của trump trong cuộc bầu cử năm 2020, gây nguy hiểm cho hiến pháp mỹ, an ninh quốc gia và tính công bằng của bầu cử.
